### ISSUE TITLE
API design improvements

### ISSUE THREAD

**Issue by miho** [bernardladenthin/streambuffer#5]
**Recommendation:**

The input- and output stream classes should be private.

**Explanation:**

Both SB*Stream classes only implement methods they inherit from their parent class, except for isClosed() which is not used publicly. In addition to that, manual instantiation is not needed/possible because they depend on the enclosing StreamBuffer instance. That's why I would keep those classes private.

**Comment by bernardladenthin** [comment]
Hi and thanks. I'll investigate.

**Comment by bernardladenthin** [comment]
Thanks, it's commited.
